Assignment 1 Submission
chase-michael/CS50 pull request #1
Opened 2020-09-16 17:22 UTC by chase-michael

2020-09-17 00:41 UTC, kbhuwalka commented on assignment_1/Workspace/Workspace/main.c
> +        for (int j = 0; j < height - i; j++) {
How might you combine these loops to be more concise?

2020-09-17 00:44 UTC, kbhuwalka commented on assignment_1/Workspace/Workspace/main.c
> +    coin_only = round((dollar_input - floor(dollar_input/1)) * 100);
Why do you need to divide `dollar_input` By 1?

2020-09-17 00:46 UTC, kbhuwalka commented on assignment_1/Workspace/Workspace/main.c
> +    while (coin_only - 1 >= 0)
Could this loop be eliminated since by this point there should never be more than 4 cents remaining?

2020-09-17 00:47 UTC, kbhuwalka commented on assignment_1/Workspace/Workspace/main.c
> +    while (coin_only - 25 >= 0)
Is there a better way to calculate this?
Hint: Mathematically

2020-09-17 00:49 UTC, kbhuwalka commented on assignment_1/Workspace/Workspace/main.c
> +    while (coin_only - 25 >= 0)
There is most likely a constant time solution (yours is linear — if the input was not limited to a maximum of 99 coins)

2020-09-17 00:54 UTC, kbhuwalka commented on assignment_1/Workspace/Workspace/main.c
> +    while (newccnumber / 10 > 0 || newccnumber % 10 > 0.9)
Any integer % 10 can only output 0-9. If you were trying look for all remainders  except 0, couldn’t you use this?
`newccnumber % 10 >= 1`

2020-09-17 00:55 UTC, kbhuwalka commented on assignment_1/Workspace/Workspace/main.c
> +        if (multbool == 0)
Please use Boolean here from the `stdbool` library unless your assignment instructs you otherwise.

2020-09-17 00:56 UTC, kbhuwalka commented on assignment_1/Workspace/Workspace/main.c
> +            multnumber += (newccnumber % 10) * 2;
Could this be converted to a function for readability?

2020-09-17 00:57 UTC, kbhuwalka commented on assignment_1/Workspace/Workspace/main.c
> +    if (cc_number / 10000000000000.0 < 1 && cc_number / 1000000000000 == 4) {
Is there a reason you are using floating point numbers?

2020-09-17 00:58 UTC, kbhuwalka requested changes
Please see inline comments

2020-09-17 13:11 UTC, chase-michael commented on assignment_1/Workspace/Workspace/main.c
> +        for (int j = 0; j < height - i; j++) {
I'm not sure how I can. The first one handles the lines and the second one loops through the appropriate number of spaces I need to print for that line. I can't loop through the number of spaces I need with just one loop?

2020-09-17 13:13 UTC, chase-michael commented on assignment_1/Workspace/Workspace/main.c
> +    coin_only = round((dollar_input - floor(dollar_input/1)) * 100);
I want to strip the dollar amount from the input so that I can deal with the change portion exclusively. It's a floor division to truncate the change and subtract the whole dollars. Is there a better way to do this?

2020-09-17 13:16 UTC, chase-michael commented on assignment_1/Workspace/Workspace/main.c
> +    while (coin_only - 1 >= 0)
Yes, done.

2020-09-17 13:22 UTC, kbhuwalka commented on assignment_1/Workspace/Workspace/main.c
> +    coin_only = round((dollar_input - floor(dollar_input/1)) * 100);
[This article](https://www.geeksforgeeks.org/rounding-floating-point-number-two-decimal-places-c-c/) may be a good starting point.

I would say tis should work as well:
`coin_only = round((dollar_input - floor(dollar_input)) * 100);`

2020-09-17 13:42 UTC, chase-michael commented on assignment_1/Workspace/Workspace/main.c
> +    while (coin_only - 25 >= 0)
Got it.

2020-09-17 14:00 UTC, chase-michael commented on assignment_1/Workspace/Workspace/main.c
> +    while (newccnumber / 10 > 0 || newccnumber % 10 > 0.9)
What about when a CC number has a 0 digit? `newccnumber / 10 > 0` covers that.
What about when we are checking the final (first) digit? `newccnumber % 10 > 0.9` covers that.
I could at least change that to `newccnumber % 10 >= 1`.
Thoughts?

2020-09-17 14:09 UTC, chase-michael commented on assignment_1/Workspace/Workspace/main.c
> +    if (cc_number / 10000000000000.0 < 1 && cc_number / 1000000000000 == 4) {
Dividing by int doesn't give me the decimal. I could probably also solve this with floor division.

2020-09-17 14:17 UTC, kbhuwalka commented on assignment_1/Workspace/Workspace/main.c
> +    if (cc_number / 10000000000000.0 < 1 && cc_number / 1000000000000 == 4) {
You may have to explain the logic needed here because I am not sure why you need float value.

2020-09-18 03:39 UTC, kbhuwalka approved these changes

2020-09-18 03:40 UTC, merged